### ISSUE TITLE
Use `Watching` status instead of the default `Playing`?

### ISSUE THREAD

**Issue by BrutuZ** [afonsojramos/discrakt#109]
All it takes is defining a [`{"type": 3}`](https://discord.com/developers/docs/developer-tools/game-sdk#activitytype-enum) in the activity payload.
I assume adding 
```diff
 .state(&payload_data.state) 
+.type(3) 
 .assets( 
```
to
https://github.com/afonsojramos/discrakt/blob/d5bfdb7e2621011de3b032e40ff4349ee47ebef6/src/discord.rs#L125-L126
should do it?

**Comment by Cheapek** [comment]
I would like this feature aswell but isn't `Watching` status limited only to Discord bots and it doesn't work with Rich Presence?

**Comment by BrutuZ** [comment]
Nope, it's for RPC, but I guessed the change wrong.
I've actually got it working on my fork, just need to undo a couple extraneous changes before opening a PR
![Screenshot_20241005-182021](https://github.com/user-attachments/assets/853dd41e-1377-4c44-afc1-3ee8ccf7879c)
