### ISSUE TITLE
Application name

### ISSUE THREAD

**Issue by Cheapek** [afonsojramos/discrakt#113]
### 📝 Provide a description of the new feature

Is it possible to change `TV Show/Movie` app name in Discord but also keep posters? In previous version it was possible to set `discordClientID` but there were no posters of the movies/shows.

**Comment by afonsojramos** [comment]
In theory, I don't see why this wouldn't work! But this would mean that you'd need to build it yourself as it is now built into the binary.

**Comment by Cheapek** [comment]
Yes, that did it, thank you!
