### ISSUE TITLE
Full size posters

### ISSUE THREAD

**Issue by Cheapek** [afonsojramos/discrakt#114]
### 📝 Provide a description of the new feature

Would it be possible to display posters at full size?

![Kodi](https://github.com/user-attachments/assets/10e57434-2eeb-4945-b256-958c964b13c8)

**Comment by nFin1ty** [comment]
You have to change https://github.com/afonsojramos/discrakt/blob/1d4312c5c9a73bb435912bfa1256a7db042f8aff/src/trakt.rs#L137 to `"https://image.tmdb.org/t/p/w500{}",`

and also delete these lines, as the image will still be cropped to 1:1 ratio when using small_image:
https://github.com/afonsojramos/discrakt/blob/1d4312c5c9a73bb435912bfa1256a7db042f8aff/src/discord.rs#L130-L131

**Comment by afonsojramos** [comment]
Considering that they are cropped to a 1:1 ratio I don't believe we should change this for everyone.
