### ISSUE TITLE
Suggestion: Dynamic image

### ISSUE THREAD

**Issue by Fasolovic** [afonsojramos/discrakt#25]
Hi, there is a project called "premid" and they found a way to use a dynamic cover in YTM and sound cloud,  I hope we can implement it. I think they  use URLs in place of imageKey  

[Their code](https://github.com/PreMiD/Presences/blob/main/websites/Y/YouTube%20Music/presence.ts)

Thanks

![image](https://user-images.githubusercontent.com/30713087/156552281-f6234080-0e06-4271-a929-2b1b963e5562.png)

***Update***

Even Netflix that's would be cool

[Code](https://github.com/PreMiD/Presences/tree/main/websites/N/Netflix)

![image](https://user-images.githubusercontent.com/30713087/156553656-a49acf32-c73a-427a-8716-808c84319a15.png)

**Comment by afonsojramos** [comment]
Oh man, I've heard of PreMid before, but never tried it, so this is truly very awesome! I'll look into it!

**Comment by LubricantJam** [comment]
> Oh man, I've heard of PreMid before, but never tried it, so this is truly very awesome! I'll look into it!

Any update on this? :)
