### ISSUE TITLE
Suggestion: Add ARM/ARM64 build target

### ISSUE THREAD

**Issue by drpoutine** [afonsojramos/discrakt#26]
just wanna run this on rpi instead of having to compile it every time :P would be a nice added touch to this sweet app

**Comment by afonsojramos** [comment]
Sure thing! This should be easy enough! Looking at [Rust's Platform support](https://doc.rust-lang.org/nightly/rustc/platform-support.html) it seems that for rpi the best target is `armv7-unknown-linux-gnueabihf`. I'll add it to the release process!

**Comment by afonsojramos** [comment]
Actions are down right now, but the latest PR should fix it!

**Comment by afonsojramos** [comment]
It seems that the [actions fail on arm64/aarch64](https://github.com/afonsojramos/discrakt/runs/5668354064?check_suite_focus=true). My idea is that this is happening because we are cross compiling. I will attempt to fix this with [this GitHub action](https://github.com/uraimo/run-on-arch-action).

**Comment by afonsojramos** [comment]
@drpoutine I spent more time on this than I'd like, but it is finally working flawlessly, the [new version](https://github.com/afonsojramos/discrakt/releases/latest) should already have all the arm builds (MacOS & Linux)! 🎉

**Comment by drpoutine** [comment]
> 

Thanks, sorry for the late reply. I'll spin this up before the weekend is done and check for any funky behavior :P

**Comment by drpoutine** [comment]
update to this,

darwin build works as expected. no issues
