### ISSUE TITLE
Support for private trakt profile

### ISSUE THREAD

**Issue by lluni** [afonsojramos/discrakt#35]
### 📝 Provide a description of the new feature

~discrakt could detect if the user has manually checked-in an episode or movie and show it on Discord just like how a usual scrobble is displayed. For example when watching a movie on a DVD there is no way to scrobble it so the manual check-in function can be used instead.~

**Comment by lluni** [comment]
Never mind, manual check-in is supported. I didn't notice it because my trakt profile is private.

The issue wasn't for this originally, but is it possible to use discrakt with a private profile?
Maybe an option could be to be able to log in to discrakt with OAuth, then it should be possible to detect scrobbles even with the profile set to private.

**Comment by afonsojramos** [comment]
Well, after taking a look at this it seems that it doesn't support Private profiles at all 🤷‍♂️ 

> https://trakt.docs.apiary.io/#reference/users/watching/get-watching

**Comment by lluni** [comment]
Private profiles seem to be supported actually, but it requires an OAuth:
![image](https://user-images.githubusercontent.com/36239317/221701309-1bc9d507-ea49-490a-bfda-0aadc6fa8b63.png)

The `GET watching` command also optionally supports OAuth, so that should work.

Authentication for private profile data is then done by providing an extra `Authorization` header containing an OAuth Bearer Token ([link](https://trakt.docs.apiary.io/#introduction/required-headers)), which can be generated with the following endpoint: https://trakt.docs.apiary.io/#reference/authentication-oauth/get-token

**Comment by afonsojramos** [comment]
@lluni so in short this can be done manually by users who have their private profile, right? We can also build that in discrakt, and I fully support that, so feel free to open a PR!
