### ISSUE TITLE
Nothing is being played...

### ISSUE THREAD

**Issue by zluckytraveler** [afonsojramos/discrakt#36]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

Set up my discord and trakt application and configured my file and have executed the run file, yet discord is not showing any activity. Activity status is enabled, and both applications are running on the same machine.

Output
```
Lucky@Luckys-Mac discrakt-main % chmod +x ./discrakt_darwin
Lucky@Luckys-Mac discrakt-main % ./discrakt_darwin
2022-04-27T01:50:55Z : Nothing is being played
2022-04-27T01:51:10Z : Nothing is being played
2022-04-27T01:51:25Z : Nothing is being played
2022-04-27T01:51:40Z : Nothing is being played
```

### 🪜 Steps To Reproduce

N/A

### ℹ System Info

```Markdown
Running on MacOS 

discrakt_darwin v2.2.4
```

**Comment by afonsojramos** [comment]
And you are sure that you were watching something? Because it only updates the status if you have something playing!

**Comment by zluckytraveler** [comment]
> And you are sure that you were watching something? Because it only updates the status if you have something playing!

@afonsojramos I’m absolutely 100% sure I was streaming, and that it showed I was streaming on trakt with progression as well, there is far more lines of “Nothing is being played”, I just cut it short. I streamed for an entire hour.

**Comment by afonsojramos** [comment]
@zluckytraveler do you have a private profile? That may be the reason... But I'll investigate an alternative on how to handle this in #35.

**Comment by zluckytraveler** [comment]
@afonsojramos I'm not exactly sure what you mean because all profiles whether it be on trakt, plex, or discord, they are all public profiles with no option for private profiles.

**Comment by zluckytraveler** [comment]
@afonsojramos I ended up giving it a try again, left it on for around 12 hours, and streamed throughout the entire day, watching numerous titles, anything from movies, to tv episodes, new and old, if you still would like to know, I can probably go through my trakt history, but I don’t think it’s a title issue.

**Comment by afonsojramos** [comment]
I really cannot troubleshoot this. All you need to do is fill in all of the credentials, within `credentials.ini` including the `traktUser`, maybe that's your problem?

**Comment by zluckytraveler** [comment]
> I really cannot troubleshoot this. All you need to do is fill in all of the credentials, within `credentials.ini` including the `traktUser`, maybe that's your problem?

That credentials file only has 3 requirements which I'm 100%sure is correct without a doubt, and there is no issues on that front. 

I'm not sure what the point of opening an issue is if your unable to troubleshoot or fix an issue? I've provided all the necessary information on my end, and have done everything correctly, as your instructions define.

**Comment by SlamminPig** [comment]
I'm having the same problem

**Comment by afonsojramos** [comment]
Are you sure that when it says Nothing is Playing on the CLI, if you go to [Trakt](https://trakt.tv/), something IS playing?
