### ISSUE TITLE
Further improvement of the rich presence title

### ISSUE THREAD

**Issue by apoapostolov** [afonsojramos/discrakt#37]
### 📝 Provide a description of the new feature

1. Switch to Watching verb instead of Playing 
2. Use the name of the TV Show or Movie instead the app name (as set when creating the app)

https://www.codegrepper.com/code-examples/python/discord+rich+presence+python

The goal is to achieve "Watching Star Trek" instead of "Playing Media" when the app is called Media.

**Comment by afonsojramos** [comment]
I'm pretty sure that the name cannot be dynamically changed, unfortunately...

**Comment by afonsojramos** [comment]
Yeah, looking at Discord's API Documentation it seems that it is indeed read-only: https://discord.com/developers/docs/game-sdk/activities#data-models-activity-struct

**Comment by apoapostolov** [comment]
Hello @afonsojramos and thanks for the reply.
Still, the verb can be changed right?
