### ISSUE TITLE
Customization of the verb via .ini file

### ISSUE THREAD

**Issue by apoapostolov** [afonsojramos/discrakt#38]
### 📝 Provide a description of the new feature

This is retry of #37 but only focusing on customization of the verb.
From https://discord.com/developers/docs/game-sdk/activities#data-models-activity-struct it is clear that we can use Streaming and Watching. Can we get an .ini configuration for the verb that is being used so we can set ActivityType to 1 or 3.

![image](https://user-images.githubusercontent.com/4083812/166701867-613bc804-3349-44aa-8f80-ae6cfb1b0fe5.png)

**Comment by afonsojramos** [comment]
However, right below that text you can find this:
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/19473034/167016629-ec6b2a09-e407-41c6-8a72-402f80fd2f18.png">

I'll investigate further though.

**Comment by afonsojramos** [comment]
It appears that it cannot be done at all. 😞 You can check out https://github.com/nickofolas/discord-rich-presence/issues/7 which I opened to check with the lib creator. You can also check out [PreMiD's implementation](https://github.com/PreMiD/Presences/blob/main/%40types/premid/index.d.ts#L5) with an absent ActivityType, which, if it was possible, they would be using it for sure!
