### ISSUE TITLE
IMDb and Trakt Buttons not working

### ISSUE THREAD

**Issue by GH0STDATA** [afonsojramos/discrakt#40]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

I've installed the latest version of Rust and ran `cargo run` on the main branch of Discrakt. Everything is working fine regarding the app itself and rich presence, but the IMDb and Trakt buttons are not doing anything when you click on them in Discord.

### 🪜 Steps To Reproduce

1. Install Rust
2. Open Terminal in Discrakt directory
3. Run `cargo run`
4. Play an episode of a show or a movie
5. Click on IMDb or Trakt buttons on Discord Rich Presence

### ℹ System Info

```Markdown
Windows 10 x64 (v2006)
```

**Comment by afonsojramos** [comment]
Yep, I am actually aware of this issue, but I'm almost certain that this is Discord's fault because I've had it working on other OSs.

**Comment by LastReaction** [comment]
Oh okay, so this is an error specific to the Windows ecosystem then?

**Comment by rollingmoai** [comment]
This is not a bug. Buttons **do** work, you just cannot click them on the same client where the RPC is being received.

**Comment by rollingmoai** [comment]
It seems that, as of now, I can now click links of my own buttons. @GH0STDATA can you confirm this?
