### ISSUE TITLE
Windows non-silent binary in the releases is silent

### ISSUE THREAD

**Issue by rollingmoai** [afonsojramos/discrakt#45]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

https://github.com/afonsojramos/discrakt/releases/download/v2.2.4/discrakt_win64.exe and https://github.com/afonsojramos/discrakt/releases/download/v2.2.4/discrakt_win64_silent.exe are the same exact files (checked with the hash: `8eeb71ba6c5720d932bbf720b3989a20104eeb05e05865081b693922f9184de6`). Can you fix this and publish the actual non-silent discrakt binary?

### 🪜 Steps To Reproduce

1. Download https://github.com/afonsojramos/discrakt/releases/download/v2.2.4/discrakt_win64.exe
2. Run the program and notice it run silently
3. Download https://github.com/afonsojramos/discrakt/releases/download/v2.2.4/discrakt_win64_silent.exe
4. Compare hashes with previous executable and see it matching

### ℹ System Info

```Markdown
Windows 11 22H2
```

**Comment by afonsojramos** [comment]
I have no idea how this is happening. The release process is automated and in [the `publish-win` job of `build.yml`](https://github.com/afonsojramos/discrakt/blob/main/.github/workflows/build.yml#L81) the different steps are clearly labelled. I think that the best way to solve this is to ignore the problem and just move forward with my plan of #24 which is to use [tauri](https://github.com/tauri-apps/tauri).

**Comment by sitiom** [comment]
@afonsojramos https://github.com/afonsojramos/discrakt/releases/tag/v2.2.3 doesn't have this problem. Did you somehow tinker with something in the latest release?

**Comment by afonsojramos** [comment]
Checking from the changes from [2.2.3 to 2.2.4](https://github.com/afonsojramos/discrakt/compare/v2.2.3...v2.2.4) there were a few changes that touched the releasing system, but none that would introduce such an issue. I'll due an overdue release with some updated dependencies and we'll check again on v2.2.5.

**Comment by sitiom** [comment]
Issue not present in https://github.com/afonsojramos/discrakt/releases/tag/v2.2.5, so what happened to 2.2.4 🧐

**Comment by afonsojramos** [comment]
Still, a new one arose as there was a failure in the MacOS one 😬
