### ISSUE TITLE
Built-in client IDs / API keys for Trakt, Discord, and TMDB

### ISSUE THREAD

**Issue by rollingmoai** [afonsojramos/discrakt#46]
### 📝 Provide a description of the new feature

It would be more convenient if Discrakt used preset client IDs for Trakt and Discord. You would not need to do the [Setup](https://github.com/afonsojramos/discrakt#setup) process. Just setup the Trakt user (or a `--user` flag for a no-config process) and run the application.

### ➕ Additional Information

Related to #24

**Comment by afonsojramos** [comment]
This doesn't even make sense. You can't have a default discord client id nor can you have a generic Trakt ID, it needs to be personal.

**Comment by rollingmoai** [comment]
@afonsojramos I'm not sure about trakt, but you can make your own Discord application and hard code the value in the program by default. That's how most programs do it.

**Comment by sitiom** [comment]
See trakt-scrobbler, the application ID is built-in too (https://github.com/iamkroot/trakt-scrobbler/blob/master/trakt_scrobbler/trakt_key_holder.py)! You would just have to setup an auth flow for the app (https://github.com/iamkroot/trakt-scrobbler/blob/master/trakt_scrobbler/trakt_auth.py).

**Comment by afonsojramos** [comment]
Ah, I see. Both do sound like they'd be separate issues though. And they do add some extra boilerplate, but it would make some stuff definitely easier to work with.

**Comment by afonsojramos** [comment]
@rollingmoai already hard coded the discord client id, thanks for the tip!
@sitiom I am a bit confused by that. In my mind the secret is supposed to be, as the name implies, secret. Is that not the case for Trakt Apps due to the necessity of OAuth?

**Comment by sitiom** [comment]
I just tried the latest version, and it seems like setting the client secret is not necessary for OAuth to work. See: https://security.stackexchange.com/questions/76351/whats-the-point-of-the-client-secret-in-oauth2-if-it-doesnt-need-to-be-used
