### ISSUE TITLE
Discrakt should find `credentials.ini` relative to executable path and instead of the current working directory

### ISSUE THREAD

**Issue by sitiom** [afonsojramos/discrakt#47]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

I have added `discrakt.exe` in my PATH but running it gave me this error:
```console
> discrakt
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "couldn't open credentials.ini: The system cannot find the file specified. (os error 2)"', src\utils.rs:13:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The `credentials.ini` file is inside the discrakt folder, and indeed changing my directory to that folder works. Discrakt should try to find `credentials.ini` relative to the executable path and instead on the current working directory.

### 🪜 Steps To Reproduce

1. Configure `credentials.ini`
2. Add `discrakt.exe` to the PATH
3. Running `discrakt` will fail anywhere except in the executable directory

### ℹ System Info

```Markdown
Windows 11 22H2
Discrakt v2.2.4
```
Note: Compiled it myself because of #45

**Comment by sitiom** [comment]
@afonsojramos credentials.ini is missing on the latest release. Is this expected?

**Comment by afonsojramos** [comment]
It seems to have been removed in the work of #52. Re-adding!
