### ISSUE TITLE
Bug on scrobbling a Movie

### ISSUE THREAD

**Issue by TCarneiro91** [afonsojramos/discrakt#6]
Hey, I tryed both Exe file and the python project and ending obtaining tha same result.

When i play a Series, everything is fine:
![image](https://user-images.githubusercontent.com/17798233/148681321-d219d2a1-e930-4e0b-bfa0-b6e6520e84c1.png)

But when i play a movie, nothing is presented on Discord:
![image](https://user-images.githubusercontent.com/17798233/148681409-c61b66dc-8e58-48a2-813b-b831fc67aa67.png)

But is well presented on the log:

![image](https://user-images.githubusercontent.com/17798233/148681384-6ed0bb85-4260-4964-9993-52af8804d975.png)

Can you please check what's happening?

**Comment by afonsojramos** [comment]
I have had comments about that happening before, so there is something definitely happening! 

I will investigate further over the course of the week!

**Comment by afonsojramos** [comment]
Can you test again with the new binary?

Heads up: I updated the images keys to `shows` and `movies` to follow trakt's naming.
