### ISSUE TITLE
Everything configured and does not work on MacOS

### ISSUE THREAD

**Issue by the-maty** [afonsojramos/discrakt#65]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

Hello, sorry for dumb issue post. I just dont know how to run it :D . I configured credentials.ini, made chmod +x arm64 file and if I ./file its not executing, if I do exec file , terminal window closes and its not working at all.
Can you help me resolve the issue?

### 🪜 Steps To Reproduce

chmod +x file_arm64
./file_arm64 doesnt work
exec file_arm64 (terminal window closes and its not working)

### ℹ System Info

```Markdown
MacOS
M2 Max chip
```

**Comment by afonsojramos** [comment]
Why do you say that "./file_arm64 doesnt work"?

**Comment by the-maty** [comment]
> Why do you say that "./file_arm64 doesnt work"?

The latest arm64 file doesn't work for macOS platform, the version before from 2022 arm64 (darwin) works fine. I though that arm64 is now for linux and macos as darwin was not present. So letting you know :)

**Comment by afonsojramos** [comment]
Should be working now, the builds were broken on previous releases 😅 All platforms' builds are now working again!
