### ISSUE TITLE
IMDB and Trakt buttons does not do anything

### ISSUE THREAD

**Issue by the-maty** [afonsojramos/discrakt#75]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

There was a older issue https://github.com/afonsojramos/discrakt/issues/40 
When I click on buttons nothing is happening
I also tried clicking those buttons from different accounts from different clients, same issue

### 🪜 Steps To Reproduce

I just executed LATEST (2.4.0) amr64_darwin file
everything looks working, console looks normal (screenshot) but buttons does not do anything

### ℹ System Info

```Markdown
MacOS
```

### 📸 Screenshots

<img width="412" alt="Snímek obrazovky 2024-03-06 v 18 27 52" src="https://github.com/afonsojramos/discrakt/assets/52372122/0f38471b-4c10-4e7b-8b40-1de1d87a4d46">
https://streamable.com/xjuwju

**Comment by afonsojramos** [comment]
<img width="359" alt="image" src="https://github.com/afonsojramos/discrakt/assets/19473034/ffd246ab-b13a-4850-b7e3-43b2cfd820fe">
<img width="454" alt="image" src="https://github.com/afonsojramos/discrakt/assets/19473034/63f66daf-271d-47f1-a4a1-b855434a3fc2">

**Comment by the-maty** [comment]
👍🏻, thanks for the info

**Comment by afonsojramos** [comment]
Considering moving to a diff RPC implementation (with more recent activity) to test if this issue gets fixed: https://github.com/jewlexx/discord-presence

**Comment by afonsojramos** [comment]
@the-maty does this only happen on your own buttons or does it also not work if your friends click on it?

Because apparently "buttons don't work when the user clicks on their own buttons [...] it's known that self-buttons can't be clicked (for whatever reason - discord issue)."

**Comment by the-maty** [comment]
My friends couldnt click it either

**Comment by afonsojramos** [comment]
Thanks!

**Comment by the-maty** [comment]
Well today it worked fine 😄, maybe something with rpc api? Will report if it will stop working again xd

**Comment by afonsojramos** [comment]
I'll close it in the meantime, thanks!
