### ISSUE TITLE
thread 'main' panicked at src/trakt.rs:126:34:

### ISSUE THREAD

**Issue by vnnegt** [afonsojramos/discrakt#76]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

discrakt crashes with: `thread 'main' panicked at src/trakt.rs:126:34:`

terminal output:
```
2024-03-11T01:32:59Z : Nothing is being played
2024-03-11T01:33:14Z : Nothing is being played
2024-03-11T01:33:29Z : Nothing is being played
2024-03-11T01:33:44Z : Nothing is being played
2024-03-11T01:33:59Z : Nothing is being played
2024-03-11T01:34:14Z : Nothing is being played
2024-03-11T01:34:29Z : Nothing is being played
thread 'main' panicked at src/trakt.rs:126:34:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

i'm guessing something changed with either trakt or tmdb

### 🪜 Steps To Reproduce

1. run discrakt (use the command line version to see error)
2. start video
3. wait for video to begin scrobbling
4. observe discrakt crash

i'm not sure if this happens with every video, but i've observed it happening with: `Dark Side of the Ring - S05E01`

### ℹ System Info

```Markdown
Windows: 10
discrakt: v2.4.0
```

**Comment by afonsojramos** [comment]
Is your token valid @vnnegt?

**Comment by vnnegt** [comment]
> Is your token valid @vnnegt? Can you make a request outside of discrakt?

yes it's valid and yes i can - i regenerated my key just to be sure

unfortunately it looks like discrakt doesnt crash for every video

`Dark Side of the Ring - S05E01` crashes

`Curb Your Enthusiasm - S12E06` does NOT crash

**Comment by afonsojramos** [comment]
The response is `{"id":375665,"posters":[]}`, but it shouldn't crash either way....

**Comment by afonsojramos** [comment]
@vnnegt `v2.5.0` should now work 🚀
