### ISSUE TITLE
Discord Rich Presence not showing up

### ISSUE THREAD

**Issue by ItsN3rdy** [afonsojramos/discrakt#93]
### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### 📝 Description

I have created the API per Setup instructions and configured my .ini file (added traktClientID, traktUser and traktClientSecret).
Executable and .ini file in the same folder.
I run the executable and terminal is showing and updating what I am watching.
Discord Rich Presence not showing up on my profile.

### 🪜 Steps To Reproduce

1. run discrakt (discrakt_win64.exe)
2. no Discord Rich Presence

### ℹ System Info

```Markdown
Windows 10
discrakt_win64.exe
v2.5.0
```

### 📸 Screenshots

<img width="543" alt="Screenshot 2024-05-07 205709" src="https://github.com/afonsojramos/discrakt/assets/44427435/b4c7fb48-b279-4718-8db5-125f454a9e8f">

![image](https://github.com/afonsojramos/discrakt/assets/44427435/5f17fdc9-66e8-4fe5-8cb3-2269efc21bf3)

**Comment by afonsojramos** [comment]
What do you have on Discord Settings under Activity Privacy?
<img width="779" alt="image" src="https://github.com/afonsojramos/discrakt/assets/19473034/ad7f0a57-b378-47b9-b50f-954c35603b9b">

**Comment by ItsN3rdy** [comment]
Share your detected activities with others was unchecked. That seems to have fixed it.
