### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by calmdownandcode** [afonsojramos/discrakt#99]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

it's not working after few mins it's automatically crashes

### 🪜 Steps To Reproduce

it's not working after few mins it's automatically crashes

### ℹ System Info

```Markdown
Dell G15 2023
16 gb ram
15 12th gen processer
gforce RTX 3050 grafics card
```

### 📸 Screenshots

![Screenshot 2024-05-29 210917](https://github.com/afonsojramos/discrakt/assets/168709664/0c04908f-90fc-46fb-9088-ef4029b72a67)

**Comment by afonsojramos** [comment]
Please provide reproduction steps, otherwise I can't help.
